// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/archetypes/ArchetypePreview.tsx": () => import("../components/mockups/archetypes/ArchetypePreview.tsx"),
  "./components/mockups/archetypes/ReflectionGallery.tsx": () => import("../components/mockups/archetypes/ReflectionGallery.tsx")
};
